name: CI

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - python: "3.8"
            toxenv: pyqt515-piexif-pyexiv2-cov
          - python: "3.9"
            toxenv: pyqt515
          - python: "3.10"
            toxenv: pyqt515
          - python: "3.11"
            toxenv: pyqt6
          - python: "3.11"
            toxenv: pyqt515-cov
          - python: "3.11"
            toxenv: pyqt62
          - python: "3.11"
            toxenv: pyqt63
          - python: "3.11"
            toxenv: pyqt64
          - python: "3.11"
            toxenv: pyqt65
          - python: "3.12"
            toxenv: pyqt66
          - python: "3.12"
            toxenv: pyqt6-piexif-cov
          - python: "3.12"
            toxenv: pyqt6-cov
          - python: "3.12"
            toxenv: lint
          - python: "3.12"
            toxenv: packaging
          - python: "3.12"
            toxenv: mypy-pyqt5
          - python: "3.12"
            toxenv: mypy-pyqt6
      fail-fast: false

    steps:
    - uses: actions/checkout@v4.1.5
    - uses: actions/cache@v4
      with:
        path: |
          .mypy_cache
          .tox
          ~/.cache/pip
        key: "${{ matrix.toxenv }}_${{ hashFiles('misc/requirements/requirements*.txt') }}_${{ hashFiles('scripts/maybe_build_cextension.py') }}_${{ hashFiles('scripts/lint_tests.py') }}"
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v5.1.1
      with:
        python-version: "${{ matrix.python }}"
    - name: Install dependencies
      run: |
        sudo apt-get install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libxcb-shape0 libegl1 libxcb-cursor0
        python -m pip install --upgrade pip
        pip install -r misc/requirements/requirements_tox.txt
    - name: Install dependencies for pyexiv2
      if: "contains(matrix.toxenv, 'pyexiv2')"
      run: |
        sudo apt-get install libexiv2-dev libboost-python-dev
        sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python3.so /usr/lib/x86_64-linux-gnu/libboost_python${PY//./}.so
      env:
        PY: ${{ matrix.python-version }}
    - name: Test with tox
      run: |
        tox -e "${{ matrix.toxenv }}"
      env:
        CI: Github-Actions
    - name: Upload coverage to codecov
      if: "endsWith(matrix.toxenv, '-cov')"
      uses: codecov/codecov-action@v4
      with:
        name: "${{ matrix.toxenv }}"
        token: ${{ secrets.CODECOV_TOKEN }}
