name: CI

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - python: "3.7"
            toxenv: pyqt511
          - python: "3.7"
            toxenv: pyqt512
          - python: "3.7"
            toxenv: pyqt513
          - python: "3.8"
            toxenv: pyqt513
          - python: "3.8"
            toxenv: pyqt514
          - python: "3.8"
            toxenv: pyqt515
          - python: "3.9"
            toxenv: pyqt513
          - python: "3.9"
            toxenv: pyqt514
          - python: "3.9"
            toxenv: pyqt515
          - python: "3.10"
            toxenv: pyqt515
          - python: "3.11"
            toxenv: pyqt515-cov
          - python: "3.11"
            toxenv: pyqt515-piexif-cov
          - python: "3.11"
            toxenv: pyqt6-cov
          - python: "3.11"
            toxenv: lint
          - python: "3.11"
            toxenv: packaging
          - python: "3.11"
            toxenv: mypy-pyqt5
          - python: "3.11"
            toxenv: mypy-pyqt6
      fail-fast: false

    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/cache@v3
      with:
        path: |
          .mypy_cache
          .tox
          ~/.cache/pip
        key: "${{ matrix.toxenv }}_${{ hashFiles('misc/requirements/requirements*.txt') }}_${{ hashFiles('scripts/maybe_build_cextension.py') }}_${{ hashFiles('scripts/lint_tests.py') }}"
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v4.6.1
      with:
        python-version: "${{ matrix.python }}"
    - name: Install dependencies
      run: |
        sudo apt-get install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libxcb-shape0 libegl1
        python -m pip install --upgrade pip
        pip install -r misc/requirements/requirements_tox.txt
    - name: Test with tox
      run: |
        tox -e "${{ matrix.toxenv }}"
      env:
        CI: Github-Actions
    - name: Upload coverage to codecov
      if: "endsWith(matrix.toxenv, '-cov')"
      uses: codecov/codecov-action@v3
      with:
        name: "${{ matrix.toxenv }}"
